### ISSUE TITLE
Set Xbox Controls

### ISSUE THREAD

**Issue by jadr2ddude** [jadr2ddude/HTHSRobotics#12]
Joystick for movement, maybe the back buttons for the claw, the d-pad for up and down, a button to activate calibration, and a button to hold speed/direction. Maybe?

**Comment by mattr555** [comment]
Sorry I can't make it today! Check out the [controls from last year](https://github.com/jadr2ddude/HTHSRobotics/blob/master/xbox.py), pygame works pretty well with usb controllers. [Here is the button mapping](https://www.reddit.com/r/pygame/comments/3tnm6l/xbox360_controller_class/cx80bkr). If you run the current code with default arguments it should be ok.
